-- MySQL Script generated by MySQL Workbench
-- Wed Dec  7 16:51:56 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema leebank_leelearning
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema leebank_leelearning
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `leebank_leelearning` DEFAULT CHARACTER SET utf8 ;
USE `leebank_leelearning` ;

-- -----------------------------------------------------
-- Table `leebank_leelearning`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leebank_leelearning`.`article` (
  `articleid` INT NOT NULL,
  `title` VARCHAR(64) NOT NULL,
  `subtitle` VARCHAR(155) NOT NULL,
  `content` LONGTEXT NOT NULL,
  `image` VARCHAR(155) NOT NULL,
  `articleDate` DATETIME NOT NULL,
  `createdby` VARCHAR(32) NOT NULL,
  `createdon` TIMESTAMP NOT NULL,
  `modifiedby` VARCHAR(32) NULL,
  `modifiedon` DATE NULL,
  PRIMARY KEY (`articleid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `leebank_leelearning`.`topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leebank_leelearning`.`topic` (
  `topic` VARCHAR(32) NOT NULL,
  `createdby` VARCHAR(32) NOT NULL,
  `createdon` TIMESTAMP NOT NULL,
  `modifiedby` VARCHAR(32) NULL,
  `modifiedon` DATE NULL,
  PRIMARY KEY (`topic`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `leebank_leelearning`.`articletopic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leebank_leelearning`.`articletopic` (
  `article_articleid` INT NOT NULL,
  `topic_topic` VARCHAR(32) NOT NULL,
  `createdby` VARCHAR(32) NOT NULL,
  `cratedon` TIMESTAMP NOT NULL,
  `modifiedby` VARCHAR(32) NULL,
  `modifiedon` DATE NULL,
  PRIMARY KEY (`article_articleid`, `topic_topic`),
  INDEX `fk_article_has_topic_topic1_idx` (`topic_topic` ASC) ,
  INDEX `fk_article_has_topic_article_idx` (`article_articleid` ASC) ,
  CONSTRAINT `fk_article_has_topic_article`
    FOREIGN KEY (`article_articleid`)
    REFERENCES `leebank_leelearning`.`article` (`articleid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_has_topic_topic1`
    FOREIGN KEY (`topic_topic`)
    REFERENCES `leebank_leelearning`.`topic` (`topic`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `leebank_leelearning`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leebank_leelearning`.`user` (
  `username` VARCHAR(32) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `createdby` VARCHAR(32) NOT NULL,
  `createdon` TIMESTAMP NOT NULL,
  `modifiedby` VARCHAR(32) NULL,
  `modifiedon` DATE NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `leebank_leelearning`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leebank_leelearning`.`person` (
  `personid` VARCHAR(14) NOT NULL,
  `username` VARCHAR(32) NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `birthday` DATE NOT NULL,
  `createdby` VARCHAR(32) NOT NULL,
  `createdon` TIMESTAMP NOT NULL,
  `modifiedby` VARCHAR(32) NULL,
  `modifiedon` VARCHAR(45) NULL,
  PRIMARY KEY (`personid`),
  INDEX `fk_person_user1_idx` (`username` ASC) ,
  CONSTRAINT `fk_person_user1`
    FOREIGN KEY (`username`)
    REFERENCES `leebank_leelearning`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `leebank_leelearning`.`persongroup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leebank_leelearning`.`persongroup` (
  `actualGroup` VARCHAR(32) NOT NULL,
  `createdby` VARCHAR(32) NOT NULL,
  `createdon` TIMESTAMP NOT NULL,
  `modifiedby` VARCHAR(32) NULL,
  `modifiedon` DATE NULL,
  PRIMARY KEY (`actualGroup`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `leebank_leelearning`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leebank_leelearning`.`status` (
  `status` VARCHAR(32) NOT NULL,
  `createdby` VARCHAR(32) NOT NULL,
  `createdon` TIMESTAMP NOT NULL,
  `modifiedby` VARCHAR(32) NULL,
  `modifiedon` DATE NULL,
  PRIMARY KEY (`status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `leebank_leelearning`.`persongroupperson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leebank_leelearning`.`persongroupperson` (
  `personid` VARCHAR(14) NOT NULL,
  `actualGroup` VARCHAR(32) NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `picture` VARCHAR(155) NOT NULL,
  `notes` TINYTEXT NULL,
  `createdby` VARCHAR(32) NOT NULL,
  `createdon` TIMESTAMP NOT NULL,
  `modifiedby` VARCHAR(32) NULL,
  `modifiedon` DATE NULL,
  PRIMARY KEY (`personid`, `actualGroup`),
  INDEX `fk_person_has_persongroup_persongroup1_idx` (`actualGroup` ASC) ,
  INDEX `fk_person_has_persongroup_person1_idx` (`personid` ASC) ,
  INDEX `fk_persongroupperson_status1_idx` (`status` ASC) ,
  CONSTRAINT `fk_person_has_persongroup_person1`
    FOREIGN KEY (`personid`)
    REFERENCES `leebank_leelearning`.`person` (`personid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_has_persongroup_persongroup1`
    FOREIGN KEY (`actualGroup`)
    REFERENCES `leebank_leelearning`.`persongroup` (`actualGroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_persongroupperson_status1`
    FOREIGN KEY (`status`)
    REFERENCES `leebank_leelearning`.`status` (`status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
