AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  leelearningGetArticleFull:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs16.x
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: >-
        arn:aws:iam::149908529804:role/service-role/leelearning-GetArticleFull-role-b0d47o9e
      Layers:
        - 'arn:aws:lambda:us-east-1:149908529804:layer:LeeLearning-assets:15'
      RuntimePolicy:
        UpdateRuntimeOn: Auto
